# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TotalityDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TotalityDemoApp
pod 'Moya'
pod 'ObjectMapper', '~> 3.4'


  target 'TotalityDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TotalityDemoAppUITests' do
    # Pods for testing
  end

end
